import "./globals.css";
import Nav from "./Nav";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Nav />
        {children}
        <footer className="py-4 mt-auto">
          <p className="text-center">
            &copy; {new Date().getFullYear()} All rights reserved
          </p>
        </footer>
      </body>
    </html>
  );
}
