const content = `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellendus tempora nostrum unde! Vel ab esse corrupti iure error, dicta pariatur nulla consectetur tempore, placeat rerum explicabo nobis, doloribus labore. Animi error eligendi vel quam placeat, dolores delectus suscipit. Iure recusandae deleniti aliquid? Dolores tempora reiciendis aut at fugit dolore odio?`
export const posts:IPost[] = [
    {
      id: 1,
      title: "First Post",
      content: "This is the content of the first post.\n"+content,
      comments: 10,
      likes: 25,
      writerUsername: "user123",
      writerProfilePicture: "/man-avatar-image-for-profile-png.png",
      postedAt: "2024-02-29T12:00:00Z",
      lastEditedAt: "2024-02-29T13:30:00Z",
    },
    {
      id: 2,
      title: "Second Post",
      content: "This is the content of the second post.\n"+content,
      comments: 5,
      likes: 15,
      writerUsername: "user456",
      writerProfilePicture: "/man-avatar-image-for-profile-png.png",
      postedAt: "2024-02-28T10:00:00Z",
    },
    {
      id: 3,
      title: "Third Post",
      content: "This is the content of the third post.\n"+content,
      comments: 20,
      likes: 30,
      writerUsername: "user789",
      writerProfilePicture: "/man-avatar-image-for-profile-png.png",
      postedAt: "2024-02-27T08:00:00Z",
      lastEditedAt: "2024-02-27T09:30:00Z",
    },
    {
      id: 4,
      title: "Third Post",
      content: "This is the content of the third post.\n"+content,
      comments: 20,
      likes: 30,
      writerUsername: "user789",
      writerProfilePicture: "/man-avatar-image-for-profile-png.png",
      postedAt: "2024-02-27T08:00:00Z",
      lastEditedAt: "2024-02-27T09:30:00Z",
    },
    {
      id: 5,
      title: "Third Post",
      content: "This is the content of the third post.\n"+content,
      comments: 20,
      likes: 30,
      writerUsername: "user789",
      writerProfilePicture: "/man-avatar-image-for-profile-png.png",
      postedAt: "2024-02-27T08:00:00Z",
      lastEditedAt: "2024-02-27T09:30:00Z",
    },
    {
      id: 6,
      title: "Third Post",
      content: "This is the content of the third post.\n"+content,
      comments: 20,
      likes: 30,
      writerUsername: "user789",
      writerProfilePicture: "/man-avatar-image-for-profile-png.png",
      postedAt: "2024-02-27T08:00:00Z",
      lastEditedAt: "2024-02-27T09:30:00Z",
    },
    {
      id: 7,
      title: "Third Post",
      content: "This is the content of the third post.\n"+content,
      comments: 20,
      likes: 30,
      writerUsername: "user789",
      writerProfilePicture: "/man-avatar-image-for-profile-png.png",
      postedAt: "2024-02-27T08:00:00Z",
      lastEditedAt: "2024-02-27T09:30:00Z",
    },
    {
      id: 8,
      title: "Third Post",
      content: "This is the content of the third post.\n"+content,
      comments: 20,
      likes: 30,
      writerUsername: "user789",
      writerProfilePicture: "/man-avatar-image-for-profile-png.png",
      postedAt: "2024-02-27T08:00:00Z",
      lastEditedAt: "2024-02-27T09:30:00Z",
    },
    {
      id: 9,
      title: "Third Post",
      content: "This is the content of the third post.\n"+content,
      comments: 20,
      likes: 30,
      writerUsername: "user789",
      writerProfilePicture: "/man-avatar-image-for-profile-png.png",
      postedAt: "2024-02-27T08:00:00Z",
      lastEditedAt: "2024-02-27T09:30:00Z",
    },
    {
      id: 10,
      title: "Third Post",
      content: "This is the content of the third post.\n"+content,
      comments: 20,
      likes: 30,
      writerUsername: "user789",
      writerProfilePicture: "/man-avatar-image-for-profile-png.png",
      postedAt: "2024-02-27T08:00:00Z",
      lastEditedAt: "2024-02-27T09:30:00Z",
    },
  ];